version: '3.9'

services:
  go:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    depends_on:
      - db
    tty: true

  react:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app://usr/src/app
    working_dir: /usr/src/app/
    command: sh -c "npm install && npm run start"
    tty: true

  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
